### ISSUE TITLE
使用max和min限制最大值和最小值存在BUG

### ISSUE THREAD

**Issue by asijack** [lijy91/blankapp-validation#2]
//TODO  下面2种写法会崩溃 String不能转成Number
        mValidator.add(Rule.with(mSipPort).max(65535));
        mValidator.add(Rule.with(mSipPort).required().max(65535));

 //TODO 这种写法65535限制无效
        mValidator.add(Rule.with(mSipPort).numeric().max(65535));

**Comment by lijy91** [comment]
问题已经修复，麻烦升级到 0.0.3-alpha

```
dependencies {
    compile 'org.blankapp:blankapp-validation:0.0.3-alpha@aar'
}
```
